version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx-essentia
    restart: always
    ports:
      - "84:80"
    volumes:
      - ./www:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - db
  db:
    image: mysql:5.7
    volumes:
    - /var/lib/mysql
    container_name: mysql-essentia
    ports:
    - "3366:3366"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_clientes_essentia
  php:
    build: .
    container_name: php-fpm-essentia
    volumes:
    - ./www:/www